language: php

php:
  # - 5.5.9
  # - 5.6 # Version 5.6.40 | End of Life: 10 Jan 2019
  # - 7.0 # Version 7.0.33 | End of Life: 10 Jan 2019
  # - 7.1 # Version 7.1.33 | End of Life: 1 Dec 2019
  - 7.2 # Version 7.2.30 | End of Life: 30 Nov 2020
  - 7.3 # End of Life: 6 Dec 2021
  - 7.4 # End of Life: 28 Nov 2022
  # - hhvm

env:
  #- TESTBENCH=3.7.*
  - TESTBENCH=3.8.*
  - TESTBENCH=3.*
  - TESTBENCH=4.*
  - TESTBENCH=5.*
  #- TESTBENCH=dev-master

before_install:
  #- composer remove illuminate/support illuminate/console illuminate/database \
  #  illuminate/events illuminate/filesystem illuminate/support
  - composer require --dev "phpunit/phpunit:8.*" --prefer-dist --no-update
  - composer require --dev "orchestra/testbench:${TESTBENCH}" --prefer-dist --no-update

#  if: ILLUMINATE=5.5.*
#    - composer require --dev "orchestra/testbench:3.5.*"

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: 7.2
      env: TESTBENCH=dev-master
    - php: 7.3
      env: TESTBENCH=dev-master
    - php: hhvm
      env: TESTBENCH=3.8.*
    - php: hhvm
      env: TESTBENCH=3.9.*
    - php: hhvm
      env: TESTBENCH=4.*
#  allow_failures:
#    # https://github.com/sebastianbergmann/phpunit/issues/4038
#    - php: 7.3
#      env: TESTBENCH=4.*
#    - php: 7.3
#      env: TESTBENCH=5.*
#    - php: 7.4
#      env: TESTBENCH=4.*
#    - php: 7.4
#      env: TESTBENCH=5.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  
script:
  - mkdir -p build/logs
  - phpunit --verbose --coverage-clover build/logs/clover.xml
  #  - vendor/bin/phpunit --verbose

after_success:
  - travis_retry php vendor/bin/php-coveralls

#after_script:
#  - travis_retry php vendor/bin/coveralls -v

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#poing"